### ISSUE TITLE
methoderror in docs

### ISSUE THREAD

**Issue by pdimens** [PierreBarrat/RecombTools#5]
https://github.com/PierreBarrat/TreeKnit.jl/blob/master/docs/src/options.md#L29

Gives method error instead of results

**Comment by PierreBarrat** [comment]
Thanks for pointing it out. Documentation was outdated. 

I initially used `Dict` to pass in trees because I intended the method to work for more than two trees (and wanted to keep the segment to tree mapping). But since it's now restricted to two trees, I removed this ... 

Documentation should be updated with #8, and hopefully examples will work
